name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.11"
      - name: Install dependencies
        run: |
          
                    python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest -q
